- source/facets.toml
[Jira](https://jira.mongodb.org/browse/DOCSP-35448)
[Build log](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=65f2273a6fc5f04850450e15)
[Staging link](https://preview-mongodbsarahemlin.gatsbyjs.io/java-rs/DOCSP-35448/)
> DOCSP-35448 programmatic tagging script for java rs repo

- source/get-started.txt
- source/get-started/primer.txt
- source/get-started/quickstart.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-37722>
Staging - <https://preview-mongodbrustagir.gatsbyjs.io/java-rs/DOCSP-37722-quickstart/get-started/quickstart/>
> DOCSP-37722: Quick start guide

- source/tutorials.txt
- source/tutorials/db-coll.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-37780>
Staging - <https://preview-mongodbrustagir.gatsbyjs.io/java-rs/DOCSP-37780-tutorials-db-coll/tutorials/db-coll/>
> DOCSP-37780: db collection tutorial

- source/get-started.txt
- source/get-started/pojo-qs.txt
- source/get-started/primer.txt
- source/get-started/quickstart.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-37766>
Staging - <https://preview-mongodbrustagir.gatsbyjs.io/java-rs/DOCSP-37766-pojo-qs/get-started/pojo-qs/>
> DOCSP-37766: Quick start POJOs

- .github/pull_request_template.md
- source/tutorials.txt
- source/tutorials/indexes.txt
**Note: this is a consolidation PR - the review should not be focused on style guide issues and phrasing/flow/structure**
JIRA - <https://jira.mongodb.org/browse/DOCSP-37797>
Staging - <https://preview-mongodbrustagir.gatsbyjs.io/java-rs/DOCSP-37797-indexes/tutorials/indexes/>
> DOCSP-37797: indexes tutorial

- source/tutorials.txt
- source/tutorials/aggregation.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-37835>
Staging - <https://preview-mongodbrustagir.gatsbyjs.io/java-rs/DOCSP-37835-tutorials-agg/tutorials/aggregation/>
> DOCSP-37835: aggregation tutorial

- snooty.toml
- source/tutorials.txt
- source/tutorials/bulk-writes.txt
- source/tutorials/write-ops.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-37799>
Staging -
[write ops](https://preview-mongodbrustagir.gatsbyjs.io/java-rs/DOCSP-37799-writes/tutorials/write-ops/)
[bulk writes](https://preview-mongodbrustagir.gatsbyjs.io/java-rs/DOCSP-37799-writes/tutorials/bulk-writes/)
> DOCSP-37799: writes

- source/tutorials.txt
- source/tutorials/encrypt.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-37854>
Staging - <https://preview-mongodbrustagir.gatsbyjs.io/java-rs/DOCSP-37854-encrypt/tutorials/encrypt/>
> DOCSP-37854: encryption

- source/tutorials.txt
- source/tutorials/text-search.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-37859>
Staging - <https://preview-mongodbrustagir.gatsbyjs.io/java-rs/DOCSP-37859-text-search/tutorials/text-search/>
> DOCSP-37859: text search tut

- source/get-started/pojo-qs.txt
- source/get-started/quickstart.txt
- source/tutorials.txt
- source/tutorials/aggregation.txt
- source/tutorials/change-stream.txt
- source/tutorials/connect.txt
- source/tutorials/geo.txt
- source/tutorials/read-ops.txt
- source/tutorials/write-ops.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-37860>
Staging - <https://preview-mongodbrustagir.gatsbyjs.io/java-rs/DOCSP-37860-geo/tutorials/geo/>
> DOCSP-37860: geo query tutorial

- source/get-started/pojo-qs.txt
- source/get-started/primer.txt
- source/get-started/quickstart.txt
- source/tutorials.txt
- source/tutorials/aggregation.txt
- source/tutorials/change-stream.txt
- source/tutorials/command.txt
- source/tutorials/db-coll.txt
- source/tutorials/indexes.txt
- source/tutorials/read-ops.txt
- source/tutorials/write-ops.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-37862>
Staging - <https://preview-mongodbrustagir.gatsbyjs.io/java-rs/DOCSP-37862-command/tutorials/command/>
> DOCSP-37862: command tutorial

- source/index.txt
- source/reference.txt
- source/reference/logging.txt
- source/reference/monitoring.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-37874>
Staging
- [logging](https://preview-mongodbrustagir.gatsbyjs.io/java-rs/DOCSP-37874-logging-monitoring/reference/logging/)
- [monitoring](https://preview-mongodbrustagir.gatsbyjs.io/java-rs/DOCSP-37874-logging-monitoring/reference/monitoring/)
> DOCSP-37874: logging monitoring

- source/tutorials/connect.txt
- source/tutorials/connect/tls.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-37871>
Staging - <https://preview-mongodbrustagir.gatsbyjs.io/java-rs/DOCSP-37871-tls/tutorials/connect/tls/>
> DOCSP-37871: tls tutorial

- source/tutorials/connect.txt
- source/tutorials/connect/auth.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-37872>
Staging - <https://preview-mongodbrustagir.gatsbyjs.io/java-rs/DOCSP-37872-auth/tutorials/connect/auth/>
> DOCSP-37872: auth

- source/tutorials/connect.txt
- source/tutorials/connect/auth.txt
- source/tutorials/connect/compression.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-37873>
Staging - <https://preview-mongodbrustagir.gatsbyjs.io/java-rs/DOCSP-37873-compression/tutorials/connect/compression/>
> DOCSP-37873: compression

- snooty.toml
- source/get-started/pojo-qs.txt
- source/get-started/primer.txt
- source/get-started/quickstart.txt
- source/includes/connect-section.rst
- source/includes/prereq-restaurants.rst
- source/includes/subscriber-note.rst
- source/reference/logging.txt
- source/reference/monitoring.txt
- source/tutorials/aggregation.txt
- source/tutorials/bulk-writes.txt
- source/tutorials/change-stream.txt
- source/tutorials/command.txt
- source/tutorials/connect.txt
- source/tutorials/connect/auth.txt
- source/tutorials/connect/compression.txt
- source/tutorials/connect/tls.txt
- source/tutorials/db-coll.txt
- source/tutorials/encrypt.txt
- source/tutorials/geo.txt
- source/tutorials/gridfs.txt
- source/tutorials/indexes.txt
- source/tutorials/read-ops.txt
- source/tutorials/text-search.txt
- source/tutorials/write-ops.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-37931>
Staging - https://preview-mongodbrustagir.gatsbyjs.io/java-rs/DOCSP-37931-cleanup/
> DOCSP-37931: cleanup

- source/index.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-37932>
Staging - <https://preview-mongodbrustagir.gatsbyjs.io/java-rs/DOCSP-37932-prev-versions/>
> DOCSP-37932: prev versions link

- source/index.txt
- source/whats-new.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-38806>
Staging - https://preview-mongodbrustagir.gatsbyjs.io/java-rs/DOCSP-38806-server-3.6-eol/whats-new/
> DOCSP-38806: mdb 3.6 deprecation

- source/index.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-NNNNN>
Staging - <https://docs-mongodbcom-staging.corp.mongodb.com/drivers/docsworker-xlarge/NNNNN/>
> Remove current toc

- source/index.txt
- source/issues-and-help.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-39680>
Staging - <https://preview-mongodbshuangela.gatsbyjs.io/java-rs/DOCSP-39680-issues-and-help/issues-and-help/>
> DOCSP-39680 Issues and Help page

- source/tutorials/write-update-documents.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-39696>
Staging - <https://preview-mongodbshuangela.gatsbyjs.io/java-rs/DOCSP-39696-write-update-operations/tutorials/write-update-documents/>
> DOCSP-39696 Write Update Operations

- source/connect-to-mongo/create-a-mongo-client.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-39687>
Staging - <https://preview-mongodbshuangela.gatsbyjs.io/java-rs/DOCSP-39687-create-a-mongo-client/connect-to-mongo/create-a-mongo-client/>
> DOCSP-39687 Create A Mongo Client

- source/includes/reactor-note.rst
- source/tutorials/write-delete-documents.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-39700>
Staging - <https://preview-mongodbshuangela.gatsbyjs.io/java-rs/DOCSP-39700-write-delete-operations/tutorials/write-delete-documents/>
> DOCSP-39700 Write Delete Operations

- source/index.txt
- source/validate-signatures.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-39555>
Staging - https://preview-mongodbrustagir.gatsbyjs.io/java-rs/DOCSP-39555-jvm-validate-sigs/validate-signatures/
> DOCSP-39555: java rs driver sig verification

- source/tutorials/write-update-documents.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-41448>
Staging - <https://preview-mongodbshuangela.gatsbyjs.io/java-rs/DOCSP-41448-write-update-change-code/tutorials/write-update-documents/>
> DOCSP-41448 write update change code

- source/tutorials/write-update-documents.txt
Reverts mongodb/docs-java-rs#45
> Revert "DOCSP-41448 write update change code"

- source/includes/subscriber-methods-section.rst
- source/write-operations/insert-documents.txt
Reverts mongodb/docs-java-rs#43
> Revert "DOCSP-41447 Change Write Insert Docs page to use Project Reactor"

- source/write-operations/insert-documents.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-41447>
Staging - <https://preview-mongodbshuangela.gatsbyjs.io/java-rs/DOCSP-41447-write-insert-new/write-operations/insert-documents/>
> DOCSP-41447 Write Insert Documents Technical Review

- snooty.toml
- source/write-operations/replace-documents.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-40777>
Staging - <https://preview-mongodbshuangela.gatsbyjs.io/java-rs/DOCSP-40777-write-replace-docs/write-operations/replace-documents/>
> DOCSP-40777 replace documents page

- source/write-operations/insert-documents.txt
- source/write-operations/replace-documents.txt
- source/write-operations/write-delete-documents.txt
- source/write-operations/write-update-documents.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-41795>
Staging - <https://preview-mongodbshuangela.gatsbyjs.io/java-rs/DOCSP-41795-standardize-write-pages/write-operations/insert-documents/>
<https://preview-mongodbshuangela.gatsbyjs.io/java-rs/DOCSP-41795-standardize-write-pages/write-operations/replace-documents/>
<https://preview-mongodbshuangela.gatsbyjs.io/java-rs/DOCSP-41795-standardize-write-pages/write-operations/write-delete-documents/>
<https://preview-mongodbshuangela.gatsbyjs.io/java-rs/DOCSP-41795-standardize-write-pages/write-operations/write-update-documents/>
> DOCSP-41795 standardize write pages

- source/secure-your-data.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-41830>
Staging - <https://preview-mongodbshuangela.gatsbyjs.io/java-rs/DOCSP-41830-secure-your-data-landing-page/secure-your-data/>
> DOCSP-41830 secure your data landing page

- source/whats-new.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-41578>
Staging - <https://preview-mongodbshuangela.gatsbyjs.io/java-rs/DOCSP-41578-whats-new/whats-new/>
Note: this pr is to make this page aligned with our master version of this page, so that there aren't merge conflicts when eventually merged into master.
> DOCSP-41578 whats new

- source/get-started/connect-to-mongodb.txt
- source/get-started/create-a-connection-string.txt
- source/get-started/create-a-deployment.txt
- source/get-started/download-and-install.txt
- source/getting-started.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-41682>
Staging - <https://preview-mongodbshuangela.gatsbyjs.io/java-rs/DOCSP-41682-remove-green-buttons/getting-started/>
> DOCSP-41682 remove green buttons

- source/includes/usage-examples/read-code-examples.java
- source/includes/usage-examples/sample-read-app-intro.rst
- source/includes/usage-examples/sample-read-application.java
- source/read-data-from-mongo.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-40869>
Staging - <https://preview-mongodbshuangela.gatsbyjs.io/java-rs/DOCSP-40869-read-usage-examples/read-data-from-mongo/>
> DOCSP-40869 read usage examples

- source/retrieve-data.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-39706>
Staging - <https://preview-mongodbshuangela.gatsbyjs.io/java-rs/DOCSP-39706-retrieve-data/retrieve-data/>
> DOCSP-39706 retrieve data page

- source/includes/reactor-note.rst
- source/read/count-documents.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-41757>
Staging - <https://preview-mongodbshuangela.gatsbyjs.io/java-rs/DOCSP-41757-read-count-documents/read/count-documents/>
> DOCSP-41757 read count documents

- source/read-data-from-mongo.txt
- source/write-data-to-mongo.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-42105>
Staging - <https://preview-mongodbshuangela.gatsbyjs.io/java-rs/DOCSP-42105-fix-rst-error/write-data-to-mongo/>
<https://preview-mongodbshuangela.gatsbyjs.io/java-rs/DOCSP-42105-fix-rst-error/read-data-from-mongo/>
> [DOCSP-42105] Fix rst error

- source/includes/read-ops/distinct.java
- source/read-data-from-mongo.txt
- source/read/distinct.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-39721>
Staging - <https://preview-mongodbmcmorisi.gatsbyjs.io/java-rs/DOCSP-39721-distinct/read/distinct/>
> DOCSP-39721: Distinct

- source/get-started.txt
- source/index.txt
- source/reference.txt
- source/tutorials.txt
- source/tutorials/connect.txt
- source/tutorials/write-ops.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-45560>
Staging - <https://deploy-preview-91--docs-java-rs.netlify.app/>
> DOCSP-45560 Shorten TOC v5.1

- source/write/transactions.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-45873>
Staging - <https://deploy-preview-94--docs-java-rs.netlify.app/write/transactions/>
> DOCSP-45883-parallel-operation-admonition

- source/get-started/run-sample-query.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-47974>
Staging - <https://deploy-preview-101--docs-java-rs.netlify.app/>
> DOCSP-47974 Add back previous ref

- source/index.txt
- source/read-data-from-mongo.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-48025>
Staging - https://deploy-preview-105--docs-java-rs.netlify.app/read-data-from-mongo/
> [Java RS] Remove "MongoDB" from page title

- source/read/retrieve-data.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-48205>
Staging - <https://deploy-preview-108--docs-java-rs.netlify.app/read/retrieve-data/>
> DOCSP-48205: Comment 404

- source/read-write-configuration.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-48215>
Staging - <https://deploy-preview-109--docs-java-rs.netlify.app/read-write-configuration/#read-concern>
> DOCSP-48215 404 on Read Concern

- source/includes/write/client-bulk-write.java
- source/whats-new.txt
- source/write/bulk-writes.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-46772>
Staging:
1. [whats new](https://deploy-preview-113--docs-java-rs.netlify.app/whats-new/#std-label-javars-version-5.4)
2. [bulk write](https://deploy-preview-113--docs-java-rs.netlify.app/write/bulk-writes/#client-bulk-write)
> DOCSP-46772: sort option for client bw - updateone & replaceone

- .github/pull_request_template.md
- .github/workflows/add-netlify-links.yml
JIRA - <https://jira.mongodb.org/browse/DOCSP-48769>
> DOCSP-48769 add netlify workflow

- config/redirects
JIRA - <https://jira.mongodb.org/browse/DOCSP-49130>
No pages to preview
> DOCSP-49130 - Fix redirect

- source/includes/mongodb-compatibility-table-java-rs.rst
- source/upgrade.txt
- source/whats-new.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-48773>
<li><a href=https://deploy-preview-129--docs-java-rs.netlify.app/upgrade>upgrade</a></li><li><a href=https://deploy-preview-129--docs-java-rs.netlify.app/whats-new>whats-new</a></li>
> DOCSP-48773: Server 4.0 EOL
